Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning
    Microsoft.Hosting.Lifetime: Information
NodeOptions:
  BasePath: 'C:\BrightChain'
  DatabaseName: '84791a2e97b642Dab7e404ff645d601b'
  Caches:
    - Memory
    - Disk
  BlockTypes:
    Memory:
      - Message
      - Tiny
      - Small
      - Medium
      - Large
    Disk:
      - Message
      - Tiny
      - Small
      - Medium
      - Large