name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build the Docker image
      env:
        build_tag: ${{ github.run_id }}
      run: docker build . --file BrightChain.API/Dockerfile --tag therevolutionnetwork/brightchain:${{ env.build_tag }}
    - name: Tag the shortcut repo
      env:
        build_tag: ${{ github.run_id }}
      run: docker build . --file BrightChain.API/Dockerfile --tag brightchain/core:${{ env.build_tag }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish
      env:
        DOCKER_REPO_API_SECRET: ${{ secrets.DOCKER_REPO_API_SECRET }}
        build_tag: ${{ github.run_id }}
      run: docker push therevolutionnetwork/brightchain:${{ env.build_tag }}
    - name: Publish shortcut repo
      env:
        DOCKER_REPO_API_SECRET: ${{ secrets.DOCKER_REPO_API_SECRET }}
        build_tag: ${{ github.run_id }}
      run: docker push brightchain/core:${{ env.build_tag }}